{
 "title": "ECS Task Monitoring",
 "description": "ECS Task monitoring with Prometheus and AWS Otel collector",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Running ECS Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ecs_task_cpu_reserved{aws_ecs_task_id=~\".*\"}) by (aws_ecs_task_id))"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ecs_task_memory_usage)/1024/1024"
    }
   ]
  },
  {
   "title": "Total vCPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ecs_task_cpu_usage_vcpu)" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(ecs_task_cpu_utilized[1m])) by (aws_ecs_task_family)",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(avg_over_time(ecs_task_memory_utilized[1m])) by (aws_ecs_task_family))*100/(sum(avg_over_time(ecs_task_memory_reserved[1m])) by (aws_ecs_task_family))",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(ecs_task_network_rate_rx[1m])) by (aws_ecs_task_family)",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(ecs_task_network_rate_tx[1m])) by (aws_ecs_task_family)",
     "legendFormat": "{{aws_ecs_task_family}}"
    }
   ]
  }
 ]
}